### PR TITLE
Moved to nodenv org

### PR DESCRIPTION
**Pull request by jasonkarns**

### CODE REVIEW

**Comment by jawshooah** [comment]
Why the `in progress` label? Is there anything else that needs updating before this is merged?

**Comment by jasonkarns** [comment]
those labels are created and used by waffle.io to create the kanban(esque) board. waffle.io/nodenv/nodenv

**Comment by jasonkarns** [comment]
in total, waffle.io creates and uses Backlog, Ready, In Progress, and Done labels. actually, i'm not even sure if they use a Done label since that just represents the issue being closed.

**Comment by jawshooah** [comment]
Gotcha. Merging then.

**Comment by jasonkarns** [comment]
We can edit the waffle board to have the columns we wish. For our purposes, I don't think we actually need a full kanban flow. I just use waffle so that I can see all the issues/prs across the entire nodenv org.

**Comment by jawshooah** [comment]
The Kanban flow is convenient though, and as minimal as it gets without eschewing columns completely. Might as well keep it.

**Pull request merged**
